"""conversation: add status/updated_at/token_count + text->Text

Revision ID: ec975307efab
Revises: 4dd72e18a7b5
Create Date: 2025-10-05 15:55:15.134805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec975307efab'
down_revision: Union[str, Sequence[str], None] = '4dd72e18a7b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('client_req_id', sa.String(length=64), nullable=True))
    op.add_column('conversations', sa.Column('end_reason', sa.String(length=32), nullable=True))
    op.alter_column('conversations', 'status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'complete'"),
               existing_nullable=False)
    op.alter_column('conversations', 'token_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.create_index(op.f('ix_conversations_client_req_id'), 'conversations', ['client_req_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversations_client_req_id'), table_name='conversations')
    op.alter_column('conversations', 'token_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('conversations', 'status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.drop_column('conversations', 'end_reason')
    op.drop_column('conversations', 'client_req_id')
    # ### end Alembic commands ###
